// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bquxkkaipevuakmqqilk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdXhra2FpcGV2dWFrbXFxaWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODQ4MjgsImV4cCI6MjA3MTM2MDgyOH0.fSTAjjv0D7CENU30e3XGl0GJZRF4asQ4BY5-iMRS3oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});